name: Cherry-pick merged pull request
on:
  pull_request_target:
    types: [closed]
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
jobs:
  cherry-pick:
    name: Cherry-pick pull request
    runs-on: ubuntu-latest
    if: >
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '/cherry-pick')
      )
    steps:
      - uses: actions/checkout@v6
      - name: Cherry-pick pull request
        id: cherry-pick
        uses: ./
        with:
          merge_commits: skip
      - name: Reopen PRs to trigger CI
        if: steps.cherry-pick.outputs.created_pull_numbers != ''
        env:
          GH_TOKEN: ${{ github.token }}
          PULL_NUMBERS: ${{ steps.cherry-pick.outputs.created_pull_numbers }}
        run: |
          for pr in $PULL_NUMBERS; do
            gh pr close "$pr" --repo "$GITHUB_REPOSITORY"
            gh pr reopen "$pr" --repo "$GITHUB_REPOSITORY"
          done
